CREATE USER 'Admin'@'localhost' IDENTIFIED BY 'UrqooQQh1D8Hr0ro';
GRANT ALL PRIVILEGES ON *.* TO 'Admin'@'localhost' REQUIRE NONE 
WITH GRANT OPTION MAX_QUERIES_PER_HOUR 1000 MAX_CONNECTIONS_PER_HOUR 1000 MAX_UPDATES_PER_HOUR 1000 MAX_USER_CONNECTIONS 1000;
GRANT ALL PRIVILEGES ON `applikasjon`.* TO 'Admin'@'localhost';

Admin-Passord: UrqooQQh1D8Hr0ro